### PR TITLE
prepare to release in appstore

### PR DESCRIPTION
**Pull request by violoncelloCH**
- [X] remove shipped flag
- [X] set min-version to 15 (so it can't be installed from store _and_ shipped; for 15.0.0 broken anyway)
- [X] bump version to 0.5.0 (.0 as of #30)
- [x] change Author to "Nextcloud"? --  just do be set in the appstore (https://github.com/nextcloud/app-certificate-requests/pull/208#issuecomment-450890782)

- [x] change build script for 15.0.1 to not include user_external (probably not in this PR - nextcloud/server#13225)

for #22 

cc @jancborchardt @MariusBluem @rullzer 
Signed-off-by: Jonas Sulzer <jonas@violoncello.ch>

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> * [ ]  change build script for 15.0.1 to not include user_external (probably not in this PR - [nextcloud/server#13225](https://github.com/nextcloud/server/pull/13225))

I can do this.

**Comment by MorrisJobke** [comment]
> I can do this.

But only once this is shipped to the appstore.

**Comment by MorrisJobke** [comment]
One more thing to test: check if this works properly: not that the app is then removed but not fetched from the appstore anymore.

**Comment by MorrisJobke** [comment]
> > not that the app is then removed but not fetched from the appstore anymore.
> 
> does this mean it's not installed any more by default? or what does this mean exactly?

I guess that it could be that the app code is simply not there anymore - which should be avoided.

**Comment by MorrisJobke** [comment]
> so I would need [nextcloud/app-certificate-requests#208](https://github.com/nextcloud/app-certificate-requests/pull/208) first, then we can merge this one and after that I could create the appstore release, correct?
> 
> >

Correct 👍

**Comment by violoncelloCH** [comment]
> > > not that the app is then removed but not fetched from the appstore anymore.
> > 
> > 
> > does this mean it's not installed any more by default? or what does this mean exactly?
> 
> I guess that it could be that the app code is simply not there anymore - which should be avoided.

okay, of course... do you have an idea how to avoid this?

**Comment by violoncelloCH** [comment]
> Test it extensively and report bugs (if there are any) with clear steps into the server repo.

Guess I'll need some help here, sorry.
How can I test this without a release on the appstore?

**Comment by jancborchardt** [comment]
> @jancborchardt should I change the author of this app to "Nextcloud" or not?

That’s for @MorrisJobke @rullzer to decide. I’m fine either way.

**Comment by MorrisJobke** [comment]
> * change Author to "Nextcloud"? --  just do be set in the appstore ([nextcloud/app-certificate-requests#208 (comment)](https://github.com/nextcloud/app-certificate-requests/pull/208#issuecomment-450890782))

Not needed. Just leave it as it is now.

**Comment by MorrisJobke** [comment]
> * change build script for 15.0.1 to not include user_external (probably not in this PR - [nextcloud/server#13225](https://github.com/nextcloud/server/pull/13225))

I will change it. It will not be included.

**Comment by violoncelloCH** [comment]
@MorrisJobke 
should I create a release now and publish it as soon as possible to be ready for 15.0.1 or should I wait for #30?

What's the best practice for the release? Create a tag, check out the tag, do the code signing, generate the release archive, generate a signature over the archive, create a Github release for the tag and upload it and finally paste the link and the signature to the appstore?

**Comment by MorrisJobke** [comment]
> What's the best practice for the release? Create a tag, check out the tag, do the code signing, generate the release archive, generate a signature over the archive, create a Github release for the tag and upload it and finally paste the link and the signature to the appstore?


Looks good 👍

**Comment by MorrisJobke** [comment]
> should I create a release now and publish it as soon as possible to be ready for 15.0.1 or should I wait for #30?

If it works now already then do a release now.

**Comment by violoncelloCH** [comment]
> If it works now already then do a release now.
It works already (I'll do some more tests), but the appstore documentation says that `occ app:check-code` should say that the app is "compliant" before uploading it to the appstore. Do you do checks on that and reject "non-complaint" apps?

**Comment by violoncelloCH** [comment]
@MorrisJobke
I tested it again and applied the release on a production instance (the one for our school) and everything worked fine. I then created a github release (https://github.com/nextcloud/user_external/releases/tag/v0.5.0) and uploaded the signature and the link to the archive to the appstore. Hope everything worked fine there, because I didn't get a real feedback on the upload to be completed. (There was no real feedback except a spinning circle on the "Upload" button. The form stayed with the content filled in after the spinning circle disappeared again.)  I guess it simply takes some time or need some manual steps on your (nextcloud's) side before the app becomes visible in the appstore?

**Comment by MorrisJobke** [comment]
> I guess it simply takes some time or need some manual steps on your (nextcloud's) side before the app becomes visible in the appstore?

Not really. Usually you upload the release (you did it here: https://github.com/nextcloud/user_external/releases/tag/v0.5.0) and then you open the apps.nextcloud.com page to upload an app. There you add the link to the uploaded zip and the signature and press "upload". It then checks this URL and updates the App Store right afterwards. Typically this takes 5 to 10 seconds and the app store shows it.

**Comment by violoncelloCH** [comment]
I pressed upload there and a spinner appeared on the upload button, but nothing else afterwards. I'll try it again, but I don't really know what went wrong.

**Comment by violoncelloCH** [comment]
I signed in via github. Does it have something to do with that maybe? Should I try letting me send a password reset link for the account?

the form just returns to this state, after the spinner on the upload button disappears:
image

**Comment by violoncelloCH** [comment]
is there something wrong with my signature?
because https://nextcloudappstore.readthedocs.io/en/latest/restapi.html#api-create-release shows a much shorter one as example...?

**Comment by MorrisJobke** [comment]
No - looks like an issue with the app store. Let me check that. There is usually either a success or a failure message at the top (in red or green).

**Comment by MorrisJobke** [comment]
Could you now try again?

**Comment by violoncelloCH** [comment]
still the same...
I get a 500 in network console for https://apps.nextcloud.com/api/v1/apps/releases...

**Comment by MorrisJobke** [comment]
Mmmh ... it says this:

```
tarfile.ReadError: not a gzip file
```

**Comment by MorrisJobke** [comment]
Ah ... seems that the file is corrupt. I also can't decompress it on my machine here. Just check it again and just upload again to the release.

**Comment by violoncelloCH** [comment]
ohh, I'm sorry about that! thank you for your help!
i did it with `tar -f user_external.tar.gz user_external/`... do I need to run `gzip` on that as well after `tar`?

**Comment by MorrisJobke** [comment]
https://github.com/nextcloud/jsloader/blob/master/Makefile#L60-L61

Boils down to `tar -czf FILENAME folder/`. The `-z` does the gzip compression.

**Comment by violoncelloCH** [comment]
thank you very much!
It finally worked! https://apps.nextcloud.com/apps/user_external

**Comment by MorrisJobke** [comment]
Nice 👍

**Pull request merged**
