### PR TITLE
Adding authentication via JSON REST API

### PR DESCRIPTION
**Pull request by msfuture**
Changes proposed in this pull request:
 - adding REST JSON API for external user authentication:
 - checks REST endpoint and gets optional and additional user data like groups and displayname

### CODE REVIEW

**Comment by violoncelloCH** [comment]
thanks for your contribution @msfuture 
I'll take a closer look at it as soon as I find the time to do so...

**Comment by msfuture** [comment]
By the way: I'm already testing this type of authentication with about 400 accounts involved. No errors until now, automatical group assignment made life so much easier for my colleagues.

**Comment by kesselb** [comment]
There is a wrapper for Guzzle and Curl: `IClient` (and `IClientService` as factory`). An advantage is that a proxy configuration (at config.php) is automatically used.

**Comment by violoncelloCH** [comment]
thanks for the hint @kesselb !
so that should definitely be used (also by the other backends)... @msfuture could you take a look at this?
https://github.com/nextcloud/server/blob/master/lib/private/Http/Client/Client.php

**Comment by msfuture** [comment]
I'll take a look at this!

**Comment by msfuture** [comment]
Time went by so fast... But I finally got to it.

**Pull request closed without merging**
