### PR TITLE
🚀 RELEASE: v0.11.0

### PR DESCRIPTION
**Pull request by violoncelloCH**
and make the app compatible to Nextcloud Hub 20

- [x] #152 :ok_hand: IMPROVE: move to migrations (DB)
- [ ] #153 :ok_hand: IMPROVE: make compatible to Nextcloud Hub 20 (this PR)

please review @nextcloud/user_external

### CODE REVIEW

**Comment by nickvergessen** [comment]
So in theory because you drop an old version, you should bump the major version.
Since you are below 1.0 it doesn't matter too much, but a 1.0 makes sense too, i eould go for it.

**Comment by violoncelloCH** [comment]
I don't really want to take the responsibility to promote this as "stable" but I guess it makes sense... let me update it...

**Comment by ChristophWurst** [comment]
Major in pre-1.0 basically means a minor bump. It's like major.minor.patch after 1.0 but 0.major.minor before that :wink: 

But at some point it makes sense to call this a v1.0.

**Comment by violoncelloCH** [comment]
Could we get this in, so the app doesn't get deactivated during an update to 20?

**Review by nickvergessen — APPROVED** [review]

**Pull request merged**
