### PR TITLE
Use new types introduced in Nextcloud 21 and bump compatibility

### LINKED ISSUE #165: Breaking changes in Nextcloud 21
Hi there,

I found that your app uses some classes of Nextcloud's third party libraries. Since an upgrade of those for php8 compatibility, your app will have to be adjusted as well. See https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/upgrade-guide.html#doctrine-dbal for details. Your app uses `Doctrine\DBAL\Types\Type` which lost the old constants: https://github.com/doctrine/dbal/blob/3.0.x/UPGRADE.md#deprecated-type-constants.

Cheers

### PR DESCRIPTION
**Pull request by hlnd**
Signed-off-by: Ole Morten <om@haaland.biz>

Fixes #165.

Changes proposed in this pull request:
 - Use new types.
 - Bump compatibility: I'm not intimately familiar with Nextcloud's APIs, but I suppose using this new class is going to break compatibility with Nextcloud <21.

### CODE REVIEW

**Review by brknkfr — APPROVED** [review]
Seems to work fine with a new nextcloud 21 installation.

**Comment by violoncelloCH** [comment]
Thanks for the PR @hlnd 
@ChristophWurst could you take a look if those changes make sense and if there is nothing missing? 
(That way I could hopefully create a new release next week after this is merged)

CI is failing because of #159 (which is already out of date again)

**Review by ChristophWurst — APPROVED** [review]

**Comment by almereyda** [comment]
After checking the patch, I think it might not be the best idea to change an existing migration.

On the other hand were the DBAL types removed with 21, and that migration couldn't possibly run anymore.

But will this patch also allow to take care of clients, which have existing `users_external` tables already initialized with `Type::String`, or is this kind of type migration taken care of by the NC21 upgrade migration?

**Comment by ChristophWurst** [comment]
The migration will still be run for new migrations. Existing migration files have to be touched.

**Comment by doobry-systemli** [comment]
I can verify that the app works as expected with Nextcloud 21.

Would be nice if this PR could be merged and a new app release be published @violoncelloCH :blush:

**Comment by violoncelloCH** [comment]
thanks for the PR @hlnd !

**Comment by oriolo** [comment]
Well done, It works as expected.
Just two minor issues to report with this configuration:
'<imap_server>', <port>, '<ssl/tls>', '<domain>, true, true
the user is created but no group is defined for him nor the email address.
Just in case I would also like to suggest to add a 7th parameter in which one can define the quota limit.
Thank you.

**Comment by ychaouche** [comment]
Thank you all. The red _enable untested app_ has now disappeared from the admin pannel > apps.

**Pull request merged**
