### PR TITLE
add CURL login options for IMAP Authentication

### PR DESCRIPTION
**Pull request by lazki**
Fixes https://github.com/nextcloud/user_external/issues/153

Changes proposed in this pull request:

-  add one IMAP config parameter
-  allows to choose IMAP login options

All merit goes to @qaxi and @violoncelloCH, in https://github.com/nextcloud/user_external/pull/196 and https://github.com/nextcloud/user_external/pull/176. I'm just trying to getting things done. 😃 

Signed-off-by: Federico Lazcano <flazcano@tau.org.ar>

### CODE REVIEW

**Comment by lazki** [comment]
All commits are signed off!  😆 

https://github.com/nextcloud/user_external/pull/236/checks?check_run_id=16038833484

**Comment by damnms** [comment]
any news on that?

**Comment by qaxi** [comment]
Holy crap ... Fist time I published this change it was Jul 9, 2020.

Almost 4 years later ... and it is not merged yet.

Not because, it is bad patch, but on "bureaucratic" grounds.

I tried to overcome it and failed (#176, #196), several other tried it (#236) and they are failing to these days ... sad.

**Comment by violoncelloCH** [comment]
@qaxi If you think that putting pressure on the student maintaining this app in their sparse free time will help getting this forward, you probably profoundly misunderstood something.

To the rest: sorry for not being able to review this earlier. I'll try to find some time as soon as possible.
On a side note: In general the problem with the current way config options work for this app is that it's highly inflexible since it's basically just an array passed to the class. Every change to this means a breaking change where people need to manually adapt their config. Ideally this would rather be some kind of named construct or better, it would allow for configuring the parameters via occ with some input validation as well. But this of course would mean some considerable development effort that I currently can't put into this app due to time constraints.

**Comment by qaxi** [comment]
> @qaxi If you think that putting pressure on the student maintaining this app in their sparse free time will help getting this forward, you probably profoundly misunderstood something.

No offence, but almost all of us do this kind of work in personal free time.

And is frustrating to see that the work is blocked not because it is useless or bad, but because three developers trying four years to push it to the project and are failing on ... On what we failed? I do not know, sorry. 

I work on some other projects and this one was the most frustrating push experience.

> To the rest: sorry for not being able to review this earlier. I'll try to find some time as soon as possible. 

Thanks a lot.

> On a side note: In general the problem with the current way config options work for this app is that it's highly inflexible since it's basically just an array passed to the class. Every change to this means a breaking change where people need to manually adapt their config. Ideally this would rather be some kind of named construct or better, it would allow for configuring the parameters via occ with some input validation as well. But this of course would mean some considerable development effort that I currently can't put into this app due to time constraints.

Refactoring is hard and underappreciated work. I wish you good luck with that.

**Review by qaxi — APPROVED** [review]

**Comment by qaxi** [comment]
Hi,
I am trying to help @lazki to fix php-cs lint problem by this PR o his fork ... https://github.com/lazki/user_external/pull/1

BUT, do not know if is he still interested in this PR as he is inactive for more than 7 months on GH.

Maybe you could push the change yourself.

**Comment by lazki** [comment]
I give up here. Sorry.

**Comment by damnms** [comment]
thats one of the reasons why i decided not to go with nextcloud. sad to see that bureaucracy kills interesting projects. this is very symptomatic for the complete nextcloud project. @lazki thanks for the try at least to make it better!

**Comment by qaxi** [comment]
> @qaxi it seems that your commit was not signed 🤦🏾‍♂️

Signed? What, how? ... 

OK, I give it up too. Sorry I am just ocasional pull requester to GH and live is short.

@lazki Thank you for your effort.

**Pull request closed without merging**
