### PR TITLE
Fix Querybuilder to find Users that have difference uid from displayName

### LINKED ISSUE #73: External Users not found while sharing until username (E-Mail Address) complete
### Steps to reproduce
1. Install NC 15.07 + users_external
2. Configure IMAP Server
3. Login once with an Imap user, so a record gets inserted to *users_external
4. Try to share a Directory ort File and search for the uid (aka. E-Mail Address)

### Expected behaviour
The IMAP User Record should appear after starting to type the E-Mail Address

### Actual behaviour
The IMAP User only get's displayed after entering the complete E-Mail Address

### Affected Authentication backend
IMAP

### Server configuration

**User External App version:** (see Nextcloud apps page)

0.6.1

**Operating system:**

Ubuntu 18.04

**Web server:**

Apache

**Database:**

MariaDB 10.1

**PHP version:**

7.1-7.3

**Nextcloud version:** (see Nextcloud admin page)

15.0.7

**Updated from an older Nextcloud/ownCloud or fresh install:**

Updated, but probably happens on fresh install as well.

**Where did you install Nextcloud from:**

update Channel

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.5
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.1.1
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - richdocuments: 3.2.4
  - serverinfo: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - twofactor_u2f: 2.1.3
  - updatenotification: 1.5.0
  - user_external: 0.6.1
  - workflowengine: 1.5.0
Disabled:
  - bookmarks
  - encryption
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - firstrunwizard
  - sharebymail
  - twofactor_totp
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "debug": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "X",
            "Y",
            "Z"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.7.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "defaultapp": "activity",
        "theme": "",
        "activity_expire_days": 90,
        "maintenance": false,
        "forcessl": true,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "auth.bruteforce.protection.enabled": false,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "0": "\/tmp\/redis.sock",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "user_backends": [
            {
                "class": "OC_User_IMAP",
                "arguments": [
                    "mail.niedermayr.net",
                    993,
                    "ssl",
                    ""
                ]
            }
        ],
        "loglevel": 2,
        "trashbin_retention_obligation": 30,
        "updater.release.channel": "production",
        "singleuser": false,
        "overwrite.cli.url": "https:\/\/nc.niedermayr.net",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls"
    }
}

```
</details>

#### Web server error log
<details>
<summary>Web server error log</summary>

```
IP - - [30/Apr/2019:02:51:09 +0200] "GET /ocs/v1.php/apps/files_sharing/api/v1/sharees?format=json&search=bma&perPage=200&itemType=file HTTP/1.1" 200 1444 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/73.0.3683.86 Chrome/73.0.3683.86 Safari/537.36
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Nextcloud Log stays silend
```
</details>

### LINKED ISSUE #77: users not found by display name
### Steps to reproduce
1. search for a user by display name (either in sharing dialogue or in user management)

### Expected behaviour
users should be found by display name, not only by username/uid

### Actual behaviour
you can't find users by display name anymore

---

It seems there has been either something changed in Nextcloud for 16 regarding the user search or it could also be related to the changes done to the sql queries in #30 
@nickvergessen, as you've done most of the changes in #30, do you have an idea what's going wrong here? or do you know who could be able to help me out here? because I sadly don't (yet) have much experience with databases nor with how the Nextcloud user managment is working...

What is called when a user search / lookup is done in NC?

#73 could be related to this one as well (users are only found when sharing if the complete username is entered)... so these two together make for a horrible experience when one want's to share to users from user_external :/

### PR DESCRIPTION
**Pull request by lephisto**
Fixes #73
Fixes #77

### CODE REVIEW

**Comment by violoncelloCH** [comment]
thank you for the fix! could you do a signoff on the commit? (see instructions below)

DCO is failing because the commit is not signed-off
@ could you please sign your commit? - see https://github.com/nextcloud/server/blob/master/.github/CONTRIBUTING.md#sign-your-work
can be done with `git commit --amend -s` for the last commit and then `git push -f` to push the changed commit back to github...

**Comment by lephisto** [comment]
Signed.. sorry it was like 3am, when fixing this :(

**Comment by violoncelloCH** [comment]
no problem! thanks for adding the sign-off!
I'll test this as soon as I'll find some time...

**Comment by violoncelloCH** [comment]
hmm this doesn't seem to fix the issue for me...
I still have to enter the full uid to bring up the user :/
I also discovered that there is a new issue with user search (in user management and during sharing) since NC 16 users are not found by display name any more...

**Comment by lephisto** [comment]
Thanks for merging. Helps a ton for future updates - less manual fixes .)

**Comment by violoncelloCH** [comment]
yeah thank you for figuring this out and fixing it :)

**Pull request merged**
