### PR TITLE
Add support for NC 28

### LINKED ISSUE #240: Nextcloud 28 support
IMAP authentication method work for me after edit appinfo/info.xml(36):
```
-                <nextcloud min-version="25" max-version="27" />
+                <nextcloud min-version="25" max-version="28" />
```

### PR DESCRIPTION
**Pull request by Glandos**
Fixes #240

Changes proposed in this pull request:
 - Add support for NC 28

This is untested, but only based on the success from #240

### CODE REVIEW

**Comment by hubide** [comment]
Hey dear maintener,
Any news here? I think it's just waiting an approval.

Thanks for all your work.

**Comment by madalinignisca** [comment]
It would be so lovely to see some progress towards this.

**Comment by goapunk** [comment]
@violoncelloCH any chance you could have a look at this ? :) thanks

**Review by prismopensource — APPROVED** [review]

**Comment by joe-average-user** [comment]
Would somebody please review this and allow the merge, thank you!

**Review by brknkfr — APPROVED** [review]

**Review by realizelol — APPROVED** [review]

**Review by goapunk — APPROVED** [review]

**Review by nkfilis — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
