### PR TITLE
fix long imap login delay on mailboxes with many folders

### LINKED ISSUE #145: [IMAP] long login delay on large mailboxes
### Steps to reproduce
1. enable he plugin
2. configure imap usage
3. log in with imap user with lots of directories

### Expected behaviour
login should be fast regardless of the number of directories
Fix:
add
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'CAPABILITY');
 in imap.php line 44
so only capabilities will be fetched anmd not all directories

### Affected Authentication backend
IMAP

### Server configuration

**User External App version:** (see Nextcloud apps page)
0.9.1

**Operating system:**
Ubuntu Linux 20.04

**Web server:**
Apache

**Database:**
MariaDB

**PHP version:**
7.4

**Nextcloud version:** (see Nextcloud admin page)
18.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
manual install

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here.
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

### PR DESCRIPTION
**Pull request by gagaringlg**
Fixes #145 

Changes proposed in this pull request:
 - just check imap server capabiities instead of pulling the complete folder list

### CODE REVIEW

**Comment by violoncelloCH** [comment]
thank you for your pull request!
would it be possible to sign-off on your commit? - see https://github.com/nextcloud/server/blob/master/.github/CONTRIBUTING.md#sign-your-work
can be done with `git commit --amend -s` for the last commit and then `git push -f` to push the changed commit back to github...

What worries me a bit is that, as it is called `CUSTOMREQUEST`, this could be something not supported by all imap servers and therefore break setups of other users. Do you have some reference here? How is the request processed in that case? (cc @rollbrettler on this)

**Comment by gagaringlg** [comment]
The CUSTOMREQUEST is just the way to tell curl to do something different that the default request and has nothing to do with the imap protocol

**Comment by gagaringlg** [comment]
I signed the pull request.

**Comment by gagaringlg** [comment]
The "CAPABILITY" command ist mandatory for IMAP servers.
see: https://tools.ietf.org/html/rfc3501, page 24:
6.1.    Client Commands - Any State

   The following commands are valid in any state: CAPABILITY, NOOP, and
   LOGOUT.

6.1.1.  CAPABILITY Command

   Arguments:  none

   Responses:  REQUIRED untagged response: CAPABILITY

   Result:     OK - capability completed
               BAD - command unknown or arguments invalid

      The CAPABILITY command requests a listing of capabilities that the
      server supports.  The server MUST send a single untagged
      CAPABILITY response with "IMAP4rev1" as one of the listed
      capabilities before the (tagged) OK response.

**Comment by violoncelloCH** [comment]
thanks for the clarification @gagaringlg

**Comment by violoncelloCH** [comment]
thanks for the fix!

**Pull request merged**
